//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressCal
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Zy { get; set; }
        public string ExpressID { get; set; }
    
        public virtual Express Express { get; set; }
    }
}
