//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Express
    {
        public Express()
        {
            this.ExpressCal = new HashSet<ExpressCal>();
        }
    
        public string ID { get; set; }
        public string UserID { get; set; }
        public string AddressID { get; set; }
        public decimal Money { get; set; }
        public Nullable<System.DateTime> ExpectTime { get; set; }
        public string Destination { get; set; }
        public string HamalUserID { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public int TypeID { get; set; }
        public string ExpressName { get; set; }
        public string ExpressPwd { get; set; }
        public string Phone { get; set; }
        public string Zy { get; set; }
        public int Payway { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string PickDestination { get; set; }
    
        public virtual ExpressType ExpressType { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ExpressCal> ExpressCal { get; set; }
    }
}
