//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comment = new HashSet<Comment>();
            this.Express = new HashSet<Express>();
            this.UsersAddress = new HashSet<UsersAddress>();
        }
    
        public string UserID { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public string Phone { get; set; }
        public string Icon { get; set; }
        public string AddressId { get; set; }
        public string Mail { get; set; }
        public decimal vMoney { get; set; }
        public string ParentID { get; set; }
        public System.DateTime RegTime { get; set; }
        public int UserStateId { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Express> Express { get; set; }
        public virtual UserStates UserStates { get; set; }
        public virtual ICollection<UsersAddress> UsersAddress { get; set; }
    }
}
